services:
  postgres_db:
      image: postgres:latest
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mydatabase
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        retries: 5
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  flask_app:
      build: ./flask_app
      container_name: flask_app
      restart: 
          always
      depends_on:
        - postgres_db
      environment:  
          DATABASE_USER:  postgres
          DATABASE_NAME:  mydatabase
          DATABASE_HOST:  postgres_db
          DATABASE_PASSWORD: password
      ports:
        - "5000:5000"
    
  nginx:
      image: nginx:latest
      container_name: nginx
      restart: 
        always
      depends_on:
        - flask_app
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  postgres_data:






